name: Production deployment

on:
  push:
    branches:
      - main
    
env:
  AZURE_RESOURCE_GROUP: mslearn
  AZURE_APP_PLAN: actions-ttt-deployment
  AZURE_LOCATION: '"Central US"'
  #################################################
  ### USER PROVIDED VALUES ARE REQUIRED BELOW   ###
  #################################################
  #################################################
  ### REPLACE USERNAME WITH GH USERNAME         ###
  AZURE_WEBAPP_NAME: jonathanzylstra5472-ttt-app
  #################################################
